broadlink:
  host: 192.168.1.88
  port: 8124
  device: 10039
  RMhost: 192.168.1.81
  macreverse: 'aa9078563412'
cucina:
  host: 192.168.1.88
  port: 8321
  device: 10039
  RMhost: 192.168.1.82
  macreverse: 'bb9078563412'
sala:
  host: 192.168.1.88
  port: 8322
  device: 10039
  RMhost: 192.168.1.83
  macreverse: 'cc9078563412'
commands:
  SAM-POFF: JgBGAJOVEDoQOhA6DxYPFhAVEBUQFRA6ETkROREUERQRFBEUEBUQFREUERQRORE5EBUQFRE5ETkRORE5ERUQFRA6DzsPFhAADQUAAA==
  SAM-PON:  JgBGAJKVETkRORA6ERQRFBEUERQRFBE5ETkQOhAVEBUQFREUEBUQOhEUERQRORE5EBURFBA6EBUQOhE5EBUQFRA6EDoRFBEADQUAAA==
  SAM-CHD:  JgBGAJKVEDoQOhA6ERQQFg8WDxYQFQ87EDoQOg8WDxcOFw8VDxcOFg8XDhYRFQ47EBUPFg8WDzsPPA87EDkRFBE5EjgQOhAADQUAAA==
  SAM-CHU:  JgBGAJKVEDkROhE4EBUQFg4XDBkPFw86DzsQOg8WERQPFhAVEBUQFRA5ERUPFhA6DxYQFQ8WDzoRFQ87EDoRFBA5EToQOg8ADQUAAA==
  SAM-VOLD: JgBGAJKVEDoSOBE5EBUQFREUERQRFBA6EDoROREUEBURFBEUEBUQOhE5ERQROREUEBURFBAVEBUQFRE5ERQQOhE5EDoQOhAADQUAAA==
  SAM-VOLU: JgBGAJKVETkRORA6ERQRFBAVEBUQFRA7EDkROhAUERUQFRAUEBYQOhA6EDoPFhAVEBUQFQ8WEBUPFhAVEDoQOhA6EDoQOg8ADQUAAA==
  SAM-MUTE: JgBGAJGWEDoQOhA6EBUQFREUEBURFBA6ETkRORITERQRFBEUEBURORE5ETkROREUERQTEhEUEBYPFhAVEBUQOg87EDoQOg8ADQUAAA==
  SAM-K0:   JgBGAJKVETkRORA7EBQSExEVDxUQFg87DzsTNw8WERQPFhAVDxYPOxAVEBUPFg87DxYRFBAVDxcPOhA6EDoQFRA6ETkQOhAADQUAAA==
  SAM-K1:   JgBGAJOUETkSOBE5ERQRFBEUEBUQFRE5ETkROREVDxUQFhAWDhYPFhITEDoPFg8VEBYPFg8WEDoQOhAVETkQOhA6EDoQOg8ADQUAAA==
  SAM-K2:   JgBGAJKVETkRORE5ERQQFREUERQRFBA6EjgTNxAWEBUQFRAVEBUPOxAVEDoPFhAVDxYQFRAVEBUQOhEUEDoQOhA6DzsQOhAADQUAAA==
  SAM-K3:   JgBGAJKWDzsQOg87EBUQFQ8WEBUQFRA6DzsQOg8WDxYQFRAVDxYQFRA6EDoQFRAVEBURFA8WEDoRFBEUEDoPOxA6EDoPOxAADQUAAA==
  SAM-K4:   JgBGAJKWEDoSOBA6EBUQFQ8WEBUPFg87EDoQOhAVEBUQExQTEBURFBAVEBUROREUEBURFBEUEDoRORE5EBUSOBE5ETkQOhEADQUAAA==
  SAM-K5:   JgBGAJKVETkRORE5EBUQFRAVEBUSExE5ETkROREUEBURFBAVEBURORITEBUSOBEUERQQFREUExIQOhE5EBURORE5EjgQOhEADQUAAA==
  SAM-K6:   JgBGAJKVEDoQOhE5EBURFBEUERQQFRA6ETkQOhEUEBUQFREUERQRFBE5ERQQOhAVEBUQFREUETkRFBE5EhMQOhE5ETkROREADQUAAA==
  SAM-K7:   JgBGAJKVETkROhE5DxURFQ8WERQQFRA6EDoQOhEUDxYPFg8WEBUQFREUDzsRORAVEBUQFRAVEDoSOBITERQRORE5EDoTNxEADQUAAA==
  SAM-K8:   JgBGAJOUETkRORE5EhMRFBAVEBUQFRA6EzcRORIUDxUQFRAVERQQOhAVEDoQOw8WEBQRFQ8WEBUQORIUEBURORA6EDoQOg8ADQUAAA==
  SAM-K9:   JgBGAJKVETkTNxE5ERQRFBEUERQQFRE5EDoROREUERQRFBEUDxYQFRA6ETkRORAVDxYPFhAVDzsRFBAVEBUQOhA6EDoQOg8ADQUAAA==

  LGE-POFF: JgBYAAABKpIUERQRFDUUERQRFBEUERMSEzYUNhMSEzYUNhM2FDYUNhMRFBEUERQ2ExEUERQRFBEUNRQ2FDYTEhM2FDYTNhQ2FAAFJQABKkgUAAxVAAEqSBQADQU=
  LGE-PON:  JgBYAAABKpIUERQRFDUUERQRFBEUERMSEzYUNhMSEzYUNhM2FDYUNhMRFBEUERQ2ExEUERQRFBEUNRQ2FDYTEhM2FDYTNhQ2FAAFJQABKkgUAAxVAAEqSBQADQU=
  LGE-CHD:  JgBQAAABKJMUERQRFDYTEhMRFBEUERQREzYUNhQREzYUNhQ2EzYUNhQ1FBEUERQRFBETEhMRFBEUERQ2EzYUNhQ1FDYUNhM2FAAFJgABJ0sTAA0FAAAAAAAAAAA=
  LGE-CHU:  JgBQAAABKJQSExETEjgSExEUERMSExITEjgROBITEjgROBI4EjgROBITEhMRFBETEhMSExITEhMROBI4EjgROBI4ETkROBI4EQAFKAABKEoSAA0FAAAAAAAAAAA=
  LGE-VOLD: JgBQAAABKJMTEhMSEzcSExISExIUERMSEzcTNhQREzYUNhQ2EzYUNhQ2EzYUERQRExITERQRFBEUERQREzYUNhQ1FDYUNhM2FAAFJgABKEoTAA0FAAAAAAAAAAA=
  LGE-VOLU: JgBQAAABKZIUERQRFDYTERQRFBEUERQREzYUNhQREzYUNhQ1FDYUNhMSEzYUERQRFBETERQRFBEUNhMSEzYUNhM2FDYUNhM2FAAFJgABKUkUAA0FAAAAAAAAAAA=
  LGE-MUTE: JgBQAAABKJQRFBETEjgRFBEUERMSExITEjgROBITEjgROBI4ETkROBI4ERQRExI4EhMRFBEUERMSExI4ETgSExI4ETgSOBE5EQAFKAABKEoSAA0FAAAAAAAAAAA=
  LGE-OK:   JgBYAAABKpAXERQQFTUVEBUQFRAVEBUQFTUVNRQRFDUVNRU1FTUVNRUQFBEUNRUQFRAVEBU1FRAVNRU1FBEUNRU1FTUVEBU1FQAFKAABKUkVAAxdAAEqSBUADQU=  
  LGE-K0:   JgBQAAABKpEUERQRFDYTEhMRFBEUERQRFDUUNhQRFDUUNhQ2EzYUNhQRExITERQRFDYUERMRFBEUNhQ1FDYUNhMSEzYUNhQ1FAAFJgABKUkUAA0FAAAAAAAAAAA=
  LGE-K1:   JgBQAAABKpIUERQREzYUERQRFBEUERMSEzYUNhMSEzYUNhM2FDYUNhM2FBEUERQREzYUERQRFBETEhM2FDYUNRQRFDYUNRQ2FAAFJQABKkgUAA0FAAAAAAAAAAA=
  LGE-K2:   JgBQAAABKpIUERQRFDUUERQRFBEUERQREzYUNhQREzYUNhQ1FDYUNhMSEzYUERQRFDUUERQRFBEUNRQRFDYUNRQRFDYUNhM2FAAFJgABKUkTAA0FAAAAAAAAAAA=
  LGE-K3:   JgBQAAABKpIUERMSEzYUERQRFBETERQRFDYUNRQRFDYUNRQ2FDYTNhQ2FDUUERQRFDYTEhMRFBEUERQRFDUUNhQRFDUUNhQ2EwAFJgABKkgUAA0FAAAAAAAAAAA=
  LGE-K4:   JgBQAAABKpIUERQREzYUERQRFBETEhMRFDYUNhMRFDYUNhM2FDYUNRQRFBEUNhQREzYUERQRFBETNhQ2FBETNhQRFDYTNhQ2FAAFJQABKkgUAA0FAAAAAAAAAAA=
  LGE-K5:   JgBQAAABKpIUERMRFDYUERQRExITERQRFDYUNRQRFDYUNRQ2FDYTNhQ2FBETNhQRFDYUERMRFBEUERQ2ExITNhQRFDYTNhQ2FAAFJQABKkgUAA0FAAAAAAAAAAA=
  LGE-K6:   JgBQAAABKJQRFBETEjgRFBEUERMSExITEjgROBITEjgROBI4ETgSOBEUETgSOBITEjcTEhMSExITNhMSExITNxITEjcUNhM2FAAFJQABKUkUAA0FAAAAAAAAAAA=
  LGE-K7:   JgBQAAABKpIUERMSEzYUERQRFBETERQRFDYUNRQRFDYUNhM2FDYUNRQ2FDYTNhQRFDYTEhMRFBEUERQRFBETNhQRFDYTNhQ2FAAFJQABKkgUAA0FAAAAAAAAAAA=
  LGE-K8:   JgBYAAABKpIUERQREzYUERQRFBETERQRFDYUNRQRFDYUNhM2FDYUNRQRFBEUERQ1FDYUERQRExITNhQ2FDUUERQRFDYTNhQ2FAAFJQABKUkUAAxVAAEpSRMADQU=
  LGE-K9:   JgBQAAABKpIUERMRFDYUERQRExITERQRFDYUNRQRFDYUNRQ2FDYTNhQ2FBETEhM2FDYUERMRFBEUERQ2EzYUERQRFDYTNhQ2FAAFJQABKkgUAA0FAAAAAAAAAAA=
  LGE-INP:  JgBYAAABKpIUERMSEzYUERQRFBETERQRFDYUNRQRFDYUNRQ2FDYTNhQ2FDUUERQ2FBEUERMRFBEUERQRFDUUERQ2FDYTNhQ2FAAFJQABKkgUAAxVAAEqSBQADQU=
  LGE-RED:  JgBgAAABK5ITEhQRFDUUERUQFRAVEBUQFTUUNhMSFDUVNRU1FDYTNxMSFDYUEBUQFDYSOBM3EhMTNhITFDYUNhQRFBEUERM3EQAFKwABKkgSAAxfAAErSBIADF8AAStIEwANBQAAAAAAAAAA
  LGE-GRE:  JgBYAAABKZQUERQRFDUVEBUQFRAVEBUQFTUVNRQRFDUVNRU1FTUVNRQ1FREUEBUQFTUVNRU1FRAVEBQ2FDUVNRUQFRAVEBU1FQAFKAABKkgVAAxdAAEqSRUADQU=  
  LGE-YEL:  JgBgAAABK5EUERUQFTUTEhQRFBEUERQRFDUVNRUQFTUUNhM3EzYSOBU1EzcTEhQRExITNhI4FBEUERQRFDYSOBI4ExITERQ2EgAFKgABK0gSAAxfAAEoSxIADF8AAShLEgANBQAAAAAAAAAA  
  LGE-BLU:  JgBgAAABK5ISExITEjgRFBETEhMSExITEjgSOBITEjgROBI4EjgSOBI4EhMRFBEUERMSOBI4EhMSExI4EjgROBI4EhMSExI4EgAFKgABK0gSAAxfAAEqSRQADF4AAStHFQANBQAAAAAAAAAA
    
  HIS-PON:   JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEjcSNxI3EhISNxI3EjcSNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-POFF:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEjcSNxI3EhISNxISEjcSNxISEhISEhI3EgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K0:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhISEjcSEhISEjcSNxI3EjcSNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K1:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEjcSEhISEjcSEhI3EjcSNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K2:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSEhISEjcSEhISEjcSNxISEjcSNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K3:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSEhISEjcSEhISEjcSEhISEjcSNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K4:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxISEjcSEhISEjcSNxI3EhISNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K5:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxISEjcSEhISEjcSEhI3EhISNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K6:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEjcSEhISEjcSNxISEhISNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K7:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxISEjcSEhISEjcSEhISEhISNxISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K8:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EjcSEhISEjcSNxI3EjcSEhISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-K9:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhI3EjcSEhISEjcSEhI3EjcSEhISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-UP:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISNxI3EjcSEhISEjcSNxI3EhISEhISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-DN:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxI3EjcSEhISEjcSEhI3EhISEhISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-LF:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxI3EjcSEhISEjcSNxISEhISEhISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-RG:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxI3EjcSEhISEjcSEhISEhISEhISEjcSNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-OK:  JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-VOLD: JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EhISNxISEhISNxISEjcSEhI3EhISNxI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-VOLU: JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEjcSNxISEhISNxISEjcSNxISEhISNxI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-CHD: JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxI3EjcSNxISEhISNxISEjcSEhISEhISNxI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
  HIS-CHU: JgBQAAABKJMSEhISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEhISEhI3EhISNxISEjcSNxI3EjcSEhI3EhISNxISEgAFGgABKEoSAAxWDQUAAAAAAAA=
 

